steps:
  # Build new Docker image
  - id: "build"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/personal-registry/res-req:latest"
      - "."
  # Push new Docker image to registry
  - id: "push"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/personal-registry/res-req:latest"

options:
  logging: CLOUD_LOGGING_ONLY
